export const GRANTED = 'granted'
export const DENIED = 'permission_denied'
export const NOT_FOUND = 'camera_not_found'
export const COULD_NOT_START = 'could_not_start'
export const UNKNOWN_ERROR = 'unknown_error'
